CREATE TABLE IF NOT EXISTS hotel_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_name VARCHAR(150) NOT NULL DEFAULT 'My Hotel',
  logo VARCHAR(255),
  address VARCHAR(255),
  phone VARCHAR(30),
  email VARCHAR(150),
  tax_info VARCHAR(150),
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Kolkata',
  checkin_time VARCHAR(20) NOT NULL DEFAULT '12:00 PM',
  checkout_time VARCHAR(20) NOT NULL DEFAULT '11:00 AM',
  invoice_prefix VARCHAR(10) NOT NULL DEFAULT 'INV',
  booking_prefix VARCHAR(10) NOT NULL DEFAULT 'BK',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
