CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  room_number VARCHAR(20) NOT NULL UNIQUE,
  room_type_id INT NOT NULL,
  floor VARCHAR(20),
  capacity INT NOT NULL DEFAULT 2,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  status ENUM('AVAILABLE','RESERVED','OCCUPIED','DIRTY','CLEANING','MAINTENANCE','OUT_OF_SERVICE')
    NOT NULL DEFAULT 'AVAILABLE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_type_id) REFERENCES room_types(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
