CREATE TABLE IF NOT EXISTS maintenance_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  room_id INT NOT NULL,
  issue VARCHAR(255) NOT NULL,
  status ENUM('REPORTED','ASSIGNED','IN_PROGRESS','FIXED','COMPLETED') NOT NULL DEFAULT 'REPORTED',
  assigned_to VARCHAR(150),
  notes VARCHAR(255),
  reported_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  fixed_at DATETIME,
  created_by_device VARCHAR(100),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
