module.exports = {
  ROLES: {
    ADMIN: "Admin",
    MANAGER: "Manager",
    RECEPTIONIST: "Receptionist",
    HOUSEKEEPING: "Housekeeping",
    KITCHEN: "Kitchen",
  },

  BOOKING_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CHECKED_IN: "CHECKED_IN",
    CHECKED_OUT: "CHECKED_OUT",
    CANCELLED: "CANCELLED",
    NO_SHOW: "NO_SHOW",
  },

  ROOM_STATUS: {
    AVAILABLE: "AVAILABLE",
    RESERVED: "RESERVED",
    OCCUPIED: "OCCUPIED",
    DIRTY: "DIRTY",
    CLEANING: "CLEANING",
    MAINTENANCE: "MAINTENANCE",
    OUT_OF_SERVICE: "OUT_OF_SERVICE",
  },

  PAYMENT_STATUS: {
    UNPAID: "UNPAID",
    PARTIALLY_PAID: "PARTIALLY_PAID",
    PAID: "PAID",
    REFUNDED: "REFUNDED",
  },

  FOOD_ORDER_STATUS: {
    NEW: "NEW",
    ACCEPTED: "ACCEPTED",
    PREPARING: "PREPARING",
    READY: "READY",
    DELIVERED: "DELIVERED",
    COMPLETED: "COMPLETED",
  },

  SERVICE_STATUS: {
    REQUESTED: "REQUESTED",
    ACCEPTED: "ACCEPTED",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    DELIVERED: "DELIVERED",
  },

  HOUSEKEEPING_STATUS: {
    DIRTY: "DIRTY",
    CLEANING: "CLEANING",
    INSPECTION: "INSPECTION",
    AVAILABLE: "AVAILABLE",
  },

  MAINTENANCE_STATUS: {
    REPORTED: "REPORTED",
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    FIXED: "FIXED",
    COMPLETED: "COMPLETED",
  },

  SYNC_RESULT: {
    CREATED: "created",
    UPDATED: "updated",
    FAILED: "failed",
  },
};
